# Values are encoded in base64 — it's not encryption, just encoding.
#
apiVersion: v1
kind: Secret
metadata:
  name: demo-devops-secret
  namespace: demo-devops
type: Opaque
data:
  # Placeholder value — if we going to deploying to production must replace before
  DJANGO_SECRET_KEY: Y2hhbmdlLW1lLWJlZm9yZS1kZXBsb3lpbmc=
